### ISSUE TITLE
Fix site build

### ISSUE THREAD

**Issue by holly1238** [pytorch/pytorch.github.io#1008]
Site build has been broken for a few days so new updates are not being propagated to the site: https://app.circleci.com/pipelines/github/pytorch/pytorch.github.io/21539/workflows/a0f17920-f444-4ec9-97fa-656c4e81d2ea/jobs/20649. 

https://github.com/pytorch/pytorch.github.io/pull/1002 and https://github.com/pytorch/pytorch.github.io/pull/1005 have been merged already to fix some of the errors.

@janeyx99 @malfet @svekars

**Comment by malfet** [comment]
Fixed by actually installing the updates in `bundle install` step, see https://github.com/pytorch/pytorch.github.io/commit/7d61a1bc7a66fa89501b65a49edf8009a0ba4c16
