### ISSUE TITLE
Broken Link on Start via Cloud Partners

### ISSUE THREAD

**Issue by alexjmcclure** [pytorch/pytorch.github.io#1066]
**Steps to reproduce**

1. Visit the Start via Cloud Partners page (https://pytorch.org/get-started/cloud-partners/#aws-sagemaker) 
2. Under the AWS SageMaker page, click on the link called "how to configure Amazon SageMaker with PyTorch"

**Experienced behavior**

Users are taken to this URL, which is a broken link: https://pytorch.org/get-started/cloud-partners/(https://docs.aws.amazon.com/sagemaker/latest/dg/pytorch.html)

**Expected behavior**

Users should be taken to this page: https://docs.aws.amazon.com/sagemaker/latest/dg/pytorch.html

**Comment by svekars** [comment]
This is now fixed: https://pytorch.org/get-started/cloud-partners/#aws-sagemaker
