### ISSUE TITLE
Where is documented the resize and crop in EfficientNet for torchvision v0.12.0

### ISSUE THREAD

**Issue by mjack3** [pytorch/pytorch.github.io#1071]
## 📚 Documentation

Hello, I do not see in any place what resize and center crop were done for training the efficientNet_bx models.
Where is that information? 

I saw it in the torchvision v0.13.0 documentation or code ([for example](https://github.com/pytorch/vision/blob/main/torchvision/models/efficientnet.py#L522))

Many of us have still projects in the older version.

Thanks

**Comment by svekars** [comment]
Please add this question to the [torchvision](https://github.com/pytorch/vision/issues) repo.
