### ISSUE TITLE
C++ Documentation Missing!

### ISSUE THREAD

**Issue by duanyaqi-nreal** [pytorch/pytorch.github.io#1072]
## 📚 Documentation

C++ Documentation Missing!

[https://pytorch.org/cppdocs/api/classat_1_1_tensor.html](https://pytorch.org/cppdocs/api/classat_1_1_tensor.html)

**Comment by vujadeyoon** [comment]
Dear all,

The useful link [1] is also broken.

Best,
Vujadeyoon

[1] https://pytorch.org/cppdocs/api/library_root.html

**Comment by svekars** [comment]
fixed by https://github.com/pytorch/pytorch/pull/81719
