### ISSUE TITLE
[Feature Request] SSL Certificate for pytorch.org

### ISSUE THREAD

**Issue by alanyee** [pytorch/pytorch.github.io#11]
There is a valid one `https://discuss.pytorch.org/`, and there seems to be a valid one for `https://download.pytorch.org/`. But `https://pytorch.org/` is invalid.

**Comment by soumith** [comment]
the https for pytorch.org comes from github. github pages have no proper / official way yet of having https for custom domains

**Comment by bittlingmayer** [comment]
@soumith, you're right that it's not trivial, but I have HTTPS for custom domains using GitHub Pages, for example https://vectorhack.com/, https://censormap.org.

You should just use CloudFlare: https://gist.github.com/cvan/8630f847f579f90e0c014dc5199c337b

**Comment by bittlingmayer** [comment]
I wonder if this could be causing #14.

**Comment by alanyee** [comment]
@soumith https://blog.github.com/2018-05-01-github-pages-custom-domains-https/

**Comment by soumith** [comment]
We already enabled https using the new github feature earlier this week. Hurray!!!
