### ISSUE TITLE
https redirection is not correct

### ISSUE THREAD

**Issue by lizeyan** [pytorch/pytorch.github.io#112]
## To Reproduce

Steps to reproduce the behavior (if applicable):
1. Go to 'https://pytorch.org/'
2.  Click on 'Docs'
3. We are going to 'https://pytorch.org/docs'
4. We are redirected to 'http://pytorch.org/docs/'
5. See error 'pytorch.org refused to connect'
6. Manually typing 'https://pytorch.org/docs/', and we are redirected to 'https://pytorch.org/docs/stable/index.html' and it works.

## Desktop (please complete the following information):

 - OS: macOSX mojave
 - Browser: chrome
 - Version: 69

## Additional context
Not only 'Docs', many other sections have the same issue.

**Comment by soumith** [comment]
@lizeyan I am not able to reproduce this behavior. Can you try in incognito mode, so that your local cache is erased. Also, maybe try cmd + shift + f5 (force-refresh)

**Comment by lizeyan** [comment]
> @lizeyan I am not able to reproduce this behavior. Can you try in incognito mode, so that your local cache is erased. Also, maybe try cmd + shift + f5 (force-refresh)

No, the problem still exists in incognito mode. And check the ''disable cache" does not work either.

**Comment by lizeyan** [comment]
![out](https://user-images.githubusercontent.com/12494243/48932531-79c51900-ef37-11e8-81d7-be58e7d2e79b.gif)

**Comment by soumith** [comment]
@lizeyan i'm pretty positive that this has to do with your local network / internet / VPN. We tried to reproduce this on multiple machines, but could not

**Comment by lizeyan** [comment]
In my opinion, this issue has nothing to do with you, but has something to do with GitHub Pages or my ISP. Thanks for your help anyway.
