### ISSUE TITLE
Typo in /docs/source/quantization.rst

### ISSUE THREAD

**Issue by h-grieve** [pytorch/pytorch.github.io#1139]
## 📚 Documentation

Typo `activatio nand weight are fake quantized` from `/docs/source/quantization.rst` which renders [here](https://pytorch.org/docs/stable/quantization.html).

Change to `activation and weight are fake quantized`.

**Comment by malfet** [comment]
Already fixed in https://pytorch.org/docs/1.13/quantization.html, will be promoted to stable stoon
