### ISSUE TITLE
Deep learning with pytorch is gone?

### ISSUE THREAD

**Issue by ml3082298291** [pytorch/pytorch.github.io#1257]
## To Reproduce

Steps to reproduce the behavior (if applicable):

1. There is no book, url 
                 https://pytorch.org/assets/deep-learning/Deep-Learning-with-PyTorch.pdf

**Comment by malfet** [comment]
@ml3082298291 where was it referenced from?

**Comment by msaroufim** [comment]
It's been gone for a while, last time I see it still showing up on Wayback machine was Jan 13, 2022 http://web.archive.org/web/20211121041835/https://pytorch.org/assets/deep-learning/Deep-Learning-with-PyTorch.pdf

**Comment by soumith** [comment]
it is gone by design. We only had the license to distribute it for a fixed period of time. after that, we deleted it.
