### ISSUE TITLE
Missing torchvision transforms documentation

### ISSUE THREAD

**Issue by mayoorej** [pytorch/pytorch.github.io#131]
## 📚 Documentation
pytorch  0.3.1 -> torchvision -> transforms documentation is missing. 
![screen shot 2018-11-28 at 4 20 18 pm](https://user-images.githubusercontent.com/45179858/49186210-92fc0a00-f329-11e8-9cdc-e6a63d4c7f0e.png)

**Comment by jspisak** [comment]
@mayoorej - at this point we are only supporting the docs for the latest stable binaries. You can find them here: https://pytorch.org/docs/stable/torchvision/index.html

For future releases we are considering adding versioning depending on if we have breaking changes. 

If you are good, please close this issue. Thanks!
