### ISSUE TITLE
Custom API documentation is missing

### ISSUE THREAD

**Issue by kkashilk** [pytorch/pytorch.github.io#1344]
## 🕋 Website

The `serving sdk` and `plugins` links are broken here - https://pytorch.org/serve/FAQs.html#how-can-i-add-a-custom-api-to-an-existing-framework 

## To Reproduce

Steps to reproduce the behavior (if applicable):

1. Go to ` https://pytorch.org/serve/FAQs.html#how-can-i-add-a-custom-api-to-an-existing-framework`
2. Click on [serving sdk](https://pytorch.org/serving-sdk) or [plugins](https://pytorch.org/plugins) links
3. See 404 error

## Expected behavior

Documentation on how to add custom APIs is available

## Screenshots

N/A

## Desktop (please complete the following information):

 - OS: macOS Monterey
 - Browser: firefox

## Additional context

N/A

**Comment by svekars** [comment]
Thank you for raising this issue! Can you please file in the https://github.com/pytorch/serve repo as it should be fixed there? Thanks!
