### ISSUE TITLE
Incorrect URL for python37 pip wheels

### ISSUE THREAD

**Issue by dkumor** [pytorch/pytorch.github.io#139]
## 🕋 Website

The URLs to download whl files are incorrect, giving errors:
```
$ pip install http://download.pytorch.org/whl/cu100/torch-1.0.0.post2-cp37-cp37m-linux_x86_64.whl
Could not install packages due to an EnvironmentError: 403 Client Error: Forbidden for url: http://download.pytorch.org/whl/cu100/torch-1.0.0.post2-cp37-cp37m-linux_x86_64.whl
```

I was able to install by removing the `.post2` from the URL.

## Expected behavior

The package should install without issues.

## Screenshots

![image](https://user-images.githubusercontent.com/5931166/49672536-794d7780-fa39-11e8-9844-7ef291eb38fe.png)

## Desktop (please complete the following information):

 - OS: Arch
 - Browser FF & Chrome

## Additional context
Install worked without `.post2`

**Comment by JoelMarcey** [comment]
Great catch @dkumor -- PR fix coming up.
