### ISSUE TITLE
Website front page does not say what PyTorch is

### ISSUE THREAD

**Issue by chloekek** [pytorch/pytorch.github.io#1410]
## 📚 Documentation

I came across PyTorch because I was installing some software and it appeared in the logs, so I decided to look it up and arrived on https://pytorch.org/. Unfortunately this was not enlightening, as the front page of the website does not clarify what PyTorch is. It does list: membership availability notice; links to featured reads, PyTorch 2.0, upcoming events; feature highlights; installation instructions; featured projects; community discussion channel links; but nowhere does it actually say what PyTorch is, which seems to me like quite important information for the front page of a project.

**Comment by svekars** [comment]
cc: @alenacal @cjyabraham

**Comment by alenacal** [comment]
Forwarding this along to the PyTorch marketing team so they can consider this for a front page revision. Thanks!
