### ISSUE TITLE
https://pytorch.org/cppdocs/ torch::ones instead of at::ones

### ISSUE THREAD

**Issue by gajop** [pytorch/pytorch.github.io#148]
> For example, while a tensor created with **torch::ones** will not be differentiable, a tensor created with torch::ones will be.

This should probably be written as:

> For example, while a tensor created with **at::ones** will not be differentiable, a tensor created with torch::ones will be.

**Comment by soumith** [comment]
cc: @goldsborough

**Comment by goldsborough** [comment]
Not really, we exported all symbols from the `at::` namespace into the `torch::` namespace back in October. You'll need a PyTorch version greater than 0.4 though.

**Comment by gajop** [comment]
Then I suppose that entire paragraph should be changed to include this info. In any case I hope you realize how the original docs make no sense.

**Comment by jlin27** [comment]
Paragraph corrected in the Autograd section of this page: https://pytorch.org/cppdocs/
"... For example, while a tensor created with at::ones will not be differentiable, a tensor created with torch::ones will be."
