### ISSUE TITLE
Stable Docs not updated 

### ISSUE THREAD

**Issue by surgan12** [pytorch/pytorch.github.io#150]

**Comment by brianjo** [comment]
Hi Surgan, 
Could you clarify with some more details on what you're seeing?
Thanks!

**Comment by surgan12** [comment]
like the link to pillow docs  https://pillow.readthedocs.io/en/3.4.x/handbook/concepts.html#modes
shows page does not exists.

**Comment by brianjo** [comment]
OK I see. It's on this page: https://pytorch.org/docs/stable/torchvision/transforms.html?highlight=pillow
Thanks.

**Comment by surgan12** [comment]
#149 somehow fixes it 😄😄
