### ISSUE TITLE
Confusing description of torch.multiprocessing and nn.DataParallel() in torch.distributed

### ISSUE THREAD

**Issue by leo-mao** [pytorch/pytorch.github.io#151]
## 📚 Documentation
> The torch.distributed package provides PyTorch support and communication primitives for multiprocess parallelism across several...... This differs from the kinds of parallelism provided by Multiprocessing package - torch.multiprocessing and torch.nn.DataParallel() in that it supports multiple network-connected machines and in that the user must explicitly launch a separate copy of the main training script for each process.
[source](https://pytorch.org/docs/stable/distributed.html#basics)

What do the last 2 "**that**" in "**in that**" refer to?  "`torch.multiprocessing and torch.nn.DataParallel()`" or "`torch.distributed`"?

**Comment by surgan12** [comment]
The  'in that'   refers to the torch.nn.parallel.DistributedDataparallel().

**Comment by leo-mao** [comment]
Thank you.
