### ISSUE TITLE
Ecosystem pages are missing javascript assets

### ISSUE THREAD

**Issue by colllin** [pytorch/pytorch.github.io#155]
## 🕋 Website
 
https://pytorch.org/ecosystem/elf/ looks like
<img width="1247" alt="image" src="https://user-images.githubusercontent.com/185923/50938327-f010d280-1434-11e9-8020-64dc50978f8f.png">

If it doesn't look like this for you, then you can close. 🤷‍♂️

**Comment by jlin27** [comment]
@Pat878 Added url to redirect to the elf github repo in PR https://github.com/pytorch/pytorch.github.io/pull/156
