### ISSUE TITLE
Pytorch Docs Darkmode bug?

### ISSUE THREAD

**Issue by nsk126** [pytorch/pytorch.github.io#1582]
## 🕋 Website
 Looks like the entire Pytorch Docs is in permanent dark mode? Is this intended?

## To Reproduce

Steps to reproduce the behavior (if applicable):
https://pytorch.org/docs/stable/index.html

## Screenshots
![image](https://github.com/pytorch/pytorch.github.io/assets/27050474/dd7f1005-60d9-4dc8-834d-b6b31304124d)

## Desktop (please complete the following information):

 - Browser : Chrome, Brave

**Comment by svekars** [comment]
Can't reproduce on my side.

**Comment by nsk126** [comment]
I don't understand. I opened https://pytorch.org/docs/stable/index.html on Edge, Firefox too (in private browsing) and I see the same results. Even on mobile.

**Comment by nsk126** [comment]
Looks like [ef04377](https://github.com/pytorch/pytorch.github.io/commit/ef04377d734c34eb2c97e5bb3bf30bd0caea80b9) might have been the cause. The recent revert fixed it. Thank you!
