### ISSUE TITLE
torch.random missing in the menu

### ISSUE THREAD

**Issue by rasbt** [pytorch/pytorch.github.io#162]
## 🕋 Website
 
Is there a specific reason why `torch.random` is not included in the index at https://pytorch.org/docs/stable/index.html? I think this should be added.

**Comment by jspisak** [comment]
Hi @rasbt - apologies for the delay on this. We have this on the list to fix shortly in the next release in 1H Aug. cc @brianjo

**Comment by rasbt** [comment]
Sounds good!  And no need to apologies :)
