### ISSUE TITLE
Documentation pages related to TorchRL not working

### ISSUE THREAD

**Issue by regorie** [pytorch/pytorch.github.io#1703]
## 🕋 Website
 

Links to TorchRL docs shows dead end page

## To Reproduce

Go to TorchRL documentation pages
[https://pytorch.org/rl](https://pytorch.org/rl)

Tutorial pages are also not working
[https://pytorch.org/rl/stable/tutorials/coding_ppo.html](https://pytorch.org/rl/stable/tutorials/coding_ppo.html)
[https://pytorch.org/rl/stable/tutorials/pendulum.html#](https://pytorch.org/rl/stable/tutorials/pendulum.html#)

**Comment by vmoens** [comment]
Fixed! Thanks for flagging
