### ISSUE TITLE
I can't view the source code of torchvision on the "pytorch.org/docs/stable/_modules/torchvision"

### ISSUE THREAD

**Issue by lazerliu** [pytorch/pytorch.github.io#174]
## 📚 Documentation
Excuse me,I am learning how to construct some traditional models with pytorch,and I read the source code of the relative model in torchvision on "https://pytorch.org/docs/stable/_modules/torchvision",but now I can't reach it anymore.I am wondering wheather pytorch has already ended supporting torchvison's source code on its official website"https://pytorch.org/docs/stable/_modules/torchvision".
Thank you!

**Comment by soumith** [comment]
you can read the source code here: https://github.com/pytorch/vision

**Comment by lazerliu** [comment]
> you can read the source code here: https://github.com/pytorch/vision

thanks,I read it on the website you gave the last few days.But  I still wonder whether it will be removed forever from "pytorch.docs" website.

**Comment by lazerliu** [comment]
thank you
