### ISSUE TITLE
Cannot reach "Get Started" page

### ISSUE THREAD

**Issue by skaws2003** [pytorch/pytorch.github.io#199]
## To Reproduce

Steps to reproduce the behavior (if applicable):

just click the white "Get Started" button on pytorch.org

## Expected behavior

https://pytorch.org/get-started/ should show the installation instruction, but it only directs to the dead end page

## Screenshots

![Screenshot from 2019-05-17 03-32-31](https://user-images.githubusercontent.com/30080207/57878187-7494b700-7854-11e9-9f01-bde4397bdcdc.png)

## Desktop (please complete the following information):

 - OS: Ubuntu 16.04 LTS
 - Browser: Firefox
 - Version 66.0.5(64-bit)

**Comment by mujasiyam** [comment]
1+ 
OS: Ubuntu 19.4
Browser: chrome
Version 74.0.3729.157 (Build officiel) (64 bits)

**Comment by mujasiyam** [comment]
**They have changed this link** 

_is the new link_

https://pytorch.org/get-started/locally/
