### ISSUE TITLE
Could not open Hybrid front end source page

### ISSUE THREAD

**Issue by shreepadpotadar** [pytorch/pytorch.github.io#223]
I am not able to view https://pytorch.org/docs/stable/hybridfrontend page. Its showing an error message "You have reached dead end".

**Comment by jspisak** [comment]
@shreepadpotadar - can you point me to where this is linked from on the site?

**Comment by shreepadpotadar** [comment]
@jspisak, You can find the link from this page https://pytorch.org/tutorials/beginner/ptcheat.html. In the pytorch cheatsheet, click on hybrid frontend to reproduce the raised issue.

**Comment by jspisak** [comment]
@shreepadpotadar - Thanks! I'll fix this..

**Comment by jspisak** [comment]
@shreepadpotadar - you can close this issue. I've merged a PR to fix: https://github.com/pytorch/tutorials/pull/570
