### ISSUE TITLE
Shufflenet source link misses

### ISSUE THREAD

**Issue by peterming3** [pytorch/pytorch.github.io#226]
The links to the source code of shufflenet are corrupted

**Comment by peterming3** [comment]
https://pytorch.org/docs/stable/_modules/torchvision/models/mobilenet.html#mobilenet_v2

**Comment by brianjo** [comment]
Hi @peterming3. Can you post a link to the page that you're getting that link from? I can't seem to find it. We moved some things around so if it was a bookmark it might have changed. Thanks!

**Comment by HeroicHitesh** [comment]
@peterming3 Can you please close this issue now as it's been resolved in #230
