### ISSUE TITLE
pip installs wrong version of cuda with previous versions of pytorch

### ISSUE THREAD

**Issue by josh-gleason** [pytorch/pytorch.github.io#237]
## 📚 Documentation
The pip install commands for older pytorch described [here](https://pytorch.org/get-started/previous-versions/#via-pip) don't actually install the correct version of cuda with pytorch. For example, running the following command in Ubuntu 16.04 with Python 3.7.3

`pip3 install torch==1.0.0 -f https://download.pytorch.org/whl/cu100/stablebuild`

results in

```
$ python
Python 3.7.3 (default, Apr  3 2019, 19:16:38)
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> torch.__version__
'1.0.0'
>>> torch.version.cuda
'9.0.176'
```

## Expected behavior

I expected cuda 10.0.

## Other information

I'm reporting this as a documentation error since the instructions in the old documentation worked. For example

`pip3 install https://download.pytorch.org/whl/cu100/torch-1.0.0-cp37-cp37m-linux_x86_64.whl`

results in

```
$ python
Python 3.7.3 (default, Apr  3 2019, 19:16:38)
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> torch.__version__
'1.0.0'
>>> torch.version.cuda
'10.0.130'
```

**Comment by soumith** [comment]
For versions prior to 1.2.0, we didn't realize that `pip` doesn't prioritize `-f` and just tries to install from the default registry. Hence, the wheels have to be manually downloaded via the appropriate URL in https://download.pytorch.org/whl/cu100/torch_stable.html and then `pip` installed. 


I've fixed this information via https://github.com/pytorch/pytorch.github.io/commit/06d5dc52722a7613d8993f388978e3fb503a94bb and they should be live on the website shortly.
