### ISSUE TITLE
Typo on the hybrid frontend sample code

### ISSUE THREAD

**Issue by wassimseif** [pytorch/pytorch.github.io#242]
## 📚 Documentation
I think there's a typo in this page  https://pytorch.org/features
In the torchscript section 
```python
  class MyModule(torch.rrnn.Module):
```
`torch.rrnn.Module`?  
Shouldn't it be `torch.nn.Module`

**Comment by soumith** [comment]
cc: @brianjo @jlin27

**Comment by brianjo** [comment]
Addressed in #243. Thanks for the report @wassimseif!

**Comment by brianjo** [comment]
Fix is live. https://pytorch.org/features Cheers.
