### ISSUE TITLE
Request provide TraceModel/ScriptModel API and structure detail.

### ISSUE THREAD

**Issue by joe8086** [pytorch/pytorch.github.io#259]
## 📚 Documentation

Dear Contributors,

TracedModel and ScriptModel in python is hard to access.
Because there are only a little document describe this structure.
Can you help to provide TracedModel and ScriptModel API and structure Doc for python and C++?
Then user can access them easily, and can deploy it to expect target platform.

Thanks,
8086

**Comment by soumith** [comment]
duplicate of the issue filed on pytorch/pytorch

That original issue gave a reference to our doc for the IR
