### ISSUE TITLE
Keep cuda 10.0 button in quickstart

### ISSUE THREAD

**Issue by seungwonpark** [pytorch/pytorch.github.io#292]
## 📚 Documentation

https://github.com/pytorch/pytorch.github.io/commit/c9b5b3332cbcf99e963bfb5692123c1a0be1f90e#diff-7ea25fd69a9113c141f8c799665f10f8
After this commit, CUDA 10.0 option was removed from quickstart UI.

Many users are still using CUDA 10.0 instead of 10.1. Also, there are several available options of using 10.0 instead of 10.1. However, the quickstart UI only shows 10.1 option.

In my opinion, it may mislead users to install 10.1 again even if they have 10.0 in their server. (Actually, I did.) How do you think about keeping 10.0 in quickstart UI?

![image](https://user-images.githubusercontent.com/13394294/67465810-da496280-f680-11e9-896f-2f92bdf65a55.png)

**Comment by soumith** [comment]
we plan to remove 10.0 support as 10.0 has known numerical bugs. We built 10.0 binaries for this release just to de-risk the situation

**Comment by seungwonpark** [comment]
Okay, that’s understandable. Thank you!

Seung-won Park
Undergraduate Student
Dept. of Physics and Astronomy & Computer Science Engineering
Seoul National University
yyyyy@snu.ac.kr | http://swpark.me
________________________________
