### ISSUE TITLE
Markdown for Equation Portions too small

### ISSUE THREAD

**Issue by JACOBIN-SCTCS** [pytorch/pytorch.github.io#327]
## Expected behavior

The equations are too small and is barely visible

## Screenshots
![screenshot](https://i.imgur.com/9nzXH1f.png)

## Desktop (please complete the following information):

 - OS: Kubuntu 18.04
 - Browser Google Chrome
 - Version 78.0.3904.97

**Comment by prabhuomkar** [comment]
@JACOBIN-SCTCS  can you try now with the latest version of the site? If its solved can we close this?

**Comment by JACOBIN-SCTCS** [comment]
Yes @prabhuomkar  the issue is solved
