### ISSUE TITLE
Repo license?

### ISSUE THREAD

**Issue by piskvorky** [pytorch/pytorch.github.io#35]
What's the license on this repo? I couldn't find any info.

We're thinking of modernizing the website of our open source project, the [current one](https://radimrehurek.com/gensim/) is too retro. The PyTorch web seems nice and clean, so we're thinking of using it as a starting point for customization and tweaking.

**Comment by soumith** [comment]
added via https://github.com/pytorch/pytorch.github.io/commit/4e1e81837356e12ab496998ecf53cd6b8421a7d0
