### ISSUE TITLE
TorchServe default inference handlers example links are broken

### ISSUE THREAD

**Issue by astaff** [pytorch/pytorch.github.io#375]
## 📚 Documentation

On [TORCHSERVE DEFAULT INFERENCE HANDLERS](https://pytorch.org/serve/default_handlers.html) page example links (i.e. https://pytorch.org/examples/text_classification) appear to be broken.

**Comment by dzubape** [comment]
Yes, it seems no page in https://pytorch.org/examples/ are available now

**Comment by jlin27** [comment]
The links should have pointed to the examples in github: https://github.com/pytorch/serve/tree/master/examples

I've updated the links on that page and it should be up now.
