### ISSUE TITLE
PyTorch Governance link is unreachable

### ISSUE THREAD

**Issue by khoussem** [pytorch/pytorch.github.io#385]
## 📚 Documentation

The link on https://pytorch.org/docs/stable/community/contribution_guide.html pointing to the PyTorch Governance page is unavailable.

Image to show the link

![image](https://user-images.githubusercontent.com/607068/82606403-4fe5c480-9bb7-11ea-8c26-6953cd47b7fc.png)

The page after clicking the link

https://pytorch.org/docs/source/community/governance.rst

![image](https://user-images.githubusercontent.com/607068/82606476-71df4700-9bb7-11ea-8a2e-236d138d7177.png)

**Comment by mathemage** [comment]
@khoussem @ngimel This is related to https://github.com/pytorch/pytorch/issues/37716

It's already solved there, the page will be updated in the next release.

Thanks for reporting anyway.
