### ISSUE TITLE
Docs are inaccessible/offline

### ISSUE THREAD

**Issue by sberryman** [pytorch/pytorch.github.io#440]
## 🕋 Website
 
https://pytorch.org/docs/stable/index.html

## Screenshots
<img width="1687" alt="Screen Shot 2020-07-28 at 8 53 32 AM" src="https://user-images.githubusercontent.com/324437/88689830-d20ad180-d0af-11ea-9e34-a1688a4ee302.png">

**Comment by sberryman** [comment]
I came across a repository which makes viewing the documents offline very easy!

1. https://github.com/unknownue/PyTorch.docs
1. Download the release
1. Unzip the contents
1. Open console in the path extracted and run `python -m SimpleHTTPServer 8000`
1. Visit http://localhost:8000

**Comment by samgd** [comment]
Versions <= 1.5.1 are accessible and working from the versions menu: https://pytorch.org/docs/versions.html

**Comment by jspisak** [comment]
Sorry! We are working on the issue now and will have it up shortly.
