### ISSUE TITLE
RSS/Atom feed for PyTorch blog

### ISSUE THREAD

**Issue by garar** [pytorch/pytorch.github.io#457]
## To Reproduce

Steps to reproduce the behavior (if applicable):
1. Go to: https://pytorch.org/blog/

## Expected behavior

I would love to have access to RSS/Atom feed, but it is nowhere to be found on PyTorch blog.

## Desktop (please complete the following information):

 - OS: Ubuntu 18.04
 - Browser: Firefox
 - Version: 79

## Additional context

This a feature request, not a bug.

**Comment by dhruvin2910** [comment]
#8 does exactly what you want. I think you are looking for the feed URL somewhere under /blog. It's [here](https://pytorch.org/feed) actually.

**Comment by garar** [comment]
Ooo, thank you! I will close this now.

**Comment by MaxTranced** [comment]
It would be nice if the blog had an RSS icon pointing to that URL!

**Comment by whateverforever** [comment]
thanks for the link, couldn't find it from the blog page
