### ISSUE TITLE
https://pytorch.org/serve/README.html is broken

### ISSUE THREAD

**Issue by Red-Eyed** [pytorch/pytorch.github.io#525]
## 🕋 Website

Hello 
At the https://pytorch.org/serve/README.html
Several links are broken:
* [Serving Quick Start](https://pytorch.org/README.md#serve-a-model) - Basic server usage tutorial
* [Model Archive Quick Start](https://pytorch.org/model-archiver#creating-a-model-archive) - Tutorial that shows you how to package a model archive file.
* [Installation](https://pytorch.org/README.md##install-torchserve) - Installation procedures
* [Packaging Model Archive](https://pytorch.org/model-archiver/README) - Explains how to package model archive file, use model-archiver.

And more others (check all the links please)

## To Reproduce

1. Go to all the above links
2. See error: "Oops! You've reached a dead end."

## Expected behavior

Go to the valid content

## Screenshots

![image](https://user-images.githubusercontent.com/11485451/98041863-4a113200-1e2b-11eb-9270-3ed5c1fc9b90.png)

## Desktop (please complete the following information):

 - OS: Ubuntu 20.04
 - Browser: Firefox 82.0

**Comment by brianjo** [comment]
Not sure if this file is one we need generated. I my just remove it in favor of a link to https://pytorch.org/serve. Thanks!
