### ISSUE TITLE
Wrong Get Started instructions for Windows shown by default. 

### ISSUE THREAD

**Issue by brianjo** [pytorch/pytorch.github.io#527]
## 🕋 Website
 
When visiting Get Started from Windows, the correct OS is selected in the installation table but the left navigation and page still lists MacOS instructions. 

## To Reproduce

On windows: 
1. Go to Home Page
2. Click on  Install 
3. See error

## Expected behavior

Autodetect OS and show the correct instructions. 

## Desktop (please complete the following information):

 - OS: Windows
 - Browser chrome

**Comment by ranman** [comment]
This is from this line:

+++ b/assets/get-started-sidebar.js
@@ -8,13 +8,10 @@ $([".alibaba", ".aws", ".microsoft-azure", ".google-cloud"]).each(function(index
   buildSidebarMenu(cloudPartner, "#get-started-cloud-sidebar-list");
 });

-// On start locally page load initially show the Mac OS menu
-showSidebar("macos", ".get-started-locally-sidebar li");

A very simple fix would be to simply trigger a click event:
index f57011069d8..410aec3c60e 100644
--- a/assets/quick-start-module.js
+++ b/assets/quick-start-module.js
@@ -43,11 +43,10 @@ ptbuild.on("click", function() {
 });

 // Pre-select user's operating system
-$(document).ready(function() {
+$(function() {
   var userOsOption = document.getElementById(opts.os);
-
   if (userOsOption) {
-    selectedOption(os, userOsOption, "os");
+    $(userOsOption).trigger("click")
   }
 });
