### ISSUE TITLE
Missing Link on torchvision.transforms

### ISSUE THREAD

**Issue by Wes-Wang** [pytorch/pytorch.github.io#599]
I tried to look up info in torch.transforms.Normalize, which led me to this link from Google, but it seems broken?

https://pytorch.org/docs/stable/torchvision/transforms.html

**Comment by pwais** [comment]
+1 also hit an error page redirecting to github issues

**Comment by pwais** [comment]
the whole docs site is broken: https://pytorch.org/docs/stable/torchvision shows a 404

**Comment by gergelymathe** [comment]
Yes, that's right. Can't reach docs for torchvision! :(

**Comment by aneeshnema** [comment]
This works https://pytorch.org/vision/stable/transforms.html

**Comment by CristinaMano** [comment]
+ 1. i have been trying to access from google and I get the "oops" error :) -> "Oops! You've reached a dead end and indeed, it does work going through pytorch doc and searching there...

**Comment by diniaa** [comment]
I think all documentation for torchvision moved from https://pytorch.org/docs/stable/torchvision to https://pytorch.org/vision/stable/

**Comment by niranjanrao1509** [comment]
It has been moved to https://pytorch.org/vision/stable/transforms.html :)

**Comment by Charles-Lu** [comment]
It's probably better to set a 301 redirect on the original page
