### ISSUE TITLE
Previous versions is gone

### ISSUE THREAD

**Issue by mkx1925** [pytorch/pytorch.github.io#68]
Though I try to download previous pytorch versions in the page(https://pytorch.org/previous-versions), the page is not available.
Coud you please fix it? 
Thank you.

**Comment by soumith** [comment]
hi, I can access that URL just fine. Can you please check again?

**Comment by mkx1925** [comment]
Thank you for answering my question.
Sorry, It was my carelessness.

I coundn't get the page from https://github.com/pytorch/pytorch
Maybe, URL is bit different.
https://pytorch.org/previous-versions/
https://pytorch.org/previous-versions

Thank you.

**Comment by soumith** [comment]
fixed via https://github.com/pytorch/pytorch/pull/11894
