### ISSUE TITLE
Broken link for source for torch.jit.script

### ISSUE THREAD

**Issue by psridhar-asapp** [pytorch/pytorch.github.io#734]
## 📚 Documentation

The source link is broken on https://pytorch.org/docs/stable/generated/torch.jit.script.html#torch.jit.script

Additionally, the parameters optimize=None, _frames_up=0, _rcb=None are not explained.

**Comment by malfet** [comment]
Fixed by https://github.com/pytorch/pytorch.github.io/commit/82eaa25adc292d81414e2bd33e95466c52e78dea
