### ISSUE TITLE
builds are failing

### ISSUE THREAD

**Issue by mattip** [pytorch/pytorch.github.io#853]
@brianjo, @malfet

The builds [are failing](https://app.circleci.com/pipelines/github/pytorch/pytorch.github.io/20787/workflows/fc73589c-2169-459d-8977-02acef3720c5/jobs/20007) with 
```
++ python3 ../_devel/formatter.py
++ notedown
../_devel/formatter.py:20: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  header = yaml.load(''.join(header))
Traceback (most recent call last):
  File "../_devel/formatter.py", line 33, in <module>
    if 'accelerator' in header.keys():
AttributeError: 'NoneType' object has no attribute 'keys'
Traceback (most recent call last):
  File "/usr/local/bin/notedown", line 7, in <module>
    from notedown.main import app
  File "/home/circleci/.local/lib/python3.5/site-packages/notedown/__init__.py", line 3, in <module>
    from .notedown import *
  File "/home/circleci/.local/lib/python3.5/site-packages/notedown/notedown.py", line 15, in <module>
    import nbformat.v4.nbbase as nbbase
  File "/home/circleci/.local/lib/python3.5/site-packages/nbformat/__init__.py", line 32, in <module>
    from .validator import validate, ValidationError
  File "/home/circleci/.local/lib/python3.5/site-packages/nbformat/validator.py", line 12, in <module>
    from .json_compat import get_current_validator, ValidationError
  File "/home/circleci/.local/lib/python3.5/site-packages/nbformat/json_compat.py", line 10, in <module>
    import jsonschema
  File "/home/circleci/.local/lib/python3.5/site-packages/jsonschema/__init__.py", line 56
    raise AttributeError(f"module {__name__} has no attribute {name}")
                                                                    ^
SyntaxError: invalid syntax

Exited with code exit status 1
```

I think this is due to this line in formatter.py that needs an update for a newer version of yaml https://github.com/pytorch/pytorch.github.io/blob/0fb10a7ad40f7d0255aa3a25d80fe18b1a14883a/_devel/formatter.py#L20

**Comment by mattip** [comment]
I do not have permissions to assign issues here, could someone assign it to me?

**Comment by malfet** [comment]
@mattip we should really not be using PyTorch-3.5, is there a reason we can not migrate on Python-3.6.2+ or later?

**Comment by mattip** [comment]
AFAICT the python version is coming from the circleci docker image circleci/ruby:2.5.1-node, should I update that to [cimg/2.6-node](https://circleci.com/developer/images/image/cimg/ruby) which is based on ubuntu20.04 ?

**Comment by malfet** [comment]
I wish there was a way to test those. After landing the PR I have to commit number of changes to [fix typo](https://github.com/pytorch/pytorch.github.io/commit/69f36f65498ecd0d01f2bb1fddea6ca703453b46), [update gemfile](https://github.com/pytorch/pytorch.github.io/commit/3bdfd09ee4daba94db3c88e4e64ccd9727253b22) and [update nbformat to 5.1.0](https://github.com/pytorch/pytorch.github.io/commit/e4b3e16b83dc621df746a2ad62edacaf3f01131d)

**Comment by malfet** [comment]
Everything seems to be working, so closing...

**Comment by mattip** [comment]
Sorry for the mess, thanks for fixing
