### ISSUE TITLE
1.10.1 was released, but the documentation at https://pytorch.org/docs/stable says 1.10.0

### ISSUE THREAD

**Issue by mattip** [pytorch/pytorch.github.io#898]
There are a few choices of how to fix this:
- Rename the "1.10.1" documentation to "1.10" (with no micro-version), and fix the documentation generation scripts to respect this decision going forward
- Add the "1.10.1" documentation, make it the stable version, and add it to the version selector.
- ~Rename the "1.10.0" documentation to "1.10.1"~ (probably not the best choice)

@brianjo what should the path forward be? Personally I prefer the first one, if not for 1.10 then certainly for 1.11.

**Comment by brianjo** [comment]
To be consistent, for this version  let's make the new set 1.10.1 and then on 1.11 we'll omit the last point going forward.
