### ISSUE TITLE
Different ROCm versions for Stable vs Preview (Nightly)

### ISSUE THREAD

**Issue by jithunnair-amd** [pytorch/pytorch.github.io#907]
## 📚 Documentation

The chooser on pytorch.org doesn't allow for different set of "Compute Platform"s for Stable vs Preview (Nightly) "PyTorch build" options. For ROCm, the Stable build wheels are currently with ROCm4.2 (https://download.pytorch.org/whl/rocm4.2/torch_stable.html), but the Preview (Nightly) build wheels are currently with ROCm4.3.1 (https://download.pytorch.org/whl/nightly/rocm4.3.1/torch_nightly.html). Given the ROCm release cadence, it is likely that, at various points in time, we'll have different ROCm versions for Stable vs Preview (Nightly) builds. 

Can the chooser logic be rewritten to allow for different set of Compute Platforms (or maybe other rows as well to make it generic) for different PyTorch Builds?

cc @jeffdaily @sunway513 @malfet @gb-meta

**Comment by malfet** [comment]
This does not look like a correct statement, picker already allows to one to select different versions for CUDA between nightly and stable (before 1.10 in nightly CUDA-11.3 were available, though in stable it was only 11.1)
Let me quickly write a PR that changes version for nightly from 4.2 to 4.3
