### ISSUE TITLE
Generate 1.10 documentation (with no  semvar feature version 1.10.2)

### ISSUE THREAD

**Issue by mattip** [pytorch/pytorch.github.io#917]
## 📚 Documentation

@brianjo @holly1238 

- Move the 1.10.2 documentation to 1.10
- `sed` convert the 1.10.2 version number to 1.10
- make this the stable version in version.html and in the repo (symlink)

**Comment by mattip** [comment]
Also change the scripts to not create the semver feature version 1.10.2, only 1.10

**Comment by brianjo** [comment]
@malfet FYI

**Comment by malfet** [comment]
Please note, lots of our docs now have version "1.10.1-cu102", for example https://pytorch.org/tutorials/advanced/cpp_frontend.html (wanted to file a separate issue for a while)

**Comment by mattip** [comment]
Do you see that outside the tutorials documentation?
