### ISSUE TITLE
IP address of pytorch.org listed on abuseipdb.com and blocked in some firewalls

### ISSUE THREAD

**Issue by boeddeker** [pytorch/pytorch.github.io#924]
## 🕋 Website
 

pytorch.org is blocked by some firewalls, because the IP address is on the "Malicious Site IP Address List". (I don't know that list, but my university administrator said the IP address is on that list).

## To Reproduce

Since I was not able to find "Malicious Site IP Address List", here are my steps to verify, that the IP address was reported:

First, get the IP address:
```shell
$ host pytorch.org   
pytorch.org has address 185.199.108.153
pytorch.org mail is handled by 10 alt4.aspmx.l.google.com.
pytorch.org mail is handled by 1 aspmx.l.google.com.
pytorch.org mail is handled by 5 alt1.aspmx.l.google.com.
pytorch.org mail is handled by 5 alt2.aspmx.l.google.com.
pytorch.org mail is handled by 10 alt3.aspmx.l.google.com.
$ host 185.199.108.153
153.108.199.185.in-addr.arpa domain name pointer cdn-185-199-108-153.github.com.
```
Then search for the IP address, on Google, where I found https://www.abuseipdb.com/check/185.199.108.153 .
There is denoted, that it was reported for DDos Attack, .... (See screenshots)

## Expected behavior

Open pytorch.org without a timeout error and see the website.

## Screenshots

![image](https://user-images.githubusercontent.com/13744128/152147144-5e9b465e-ff1f-4bf6-bd45-5d8a92afe430.png)

![image](https://user-images.githubusercontent.com/13744128/152147620-454f1743-9c98-4d1a-9aae-2daf1c44bb7a.png)

## Desktop (please complete the following information):

 - OS: Linux, Android
 - Browser chrome, firefox
 - Location: Germany

**Comment by albanD** [comment]
Thanks for the report, this is indeed surprising. Looking into it.
Note that the IP comes from GitHub directly so I'm surprised it ended up being blocked.

**Comment by brianjo** [comment]
@boeddeker Hi Christopher, are you able to hit other GitHub based sites like: https://reactnative.dev/ from inside your school's firewall?

**Comment by boeddeker** [comment]
> Thanks for the report, this is indeed surprising. Looking into it. Note that the IP comes from GitHub directly so I'm surprised it ended up being blocked.

Me too, but I do not know who is the correct contact for this issue. I only reported this, because the address is listed on abuseipdb.com .

> @boeddeker Hi Christopher, are you able to hit other GitHub based sites like: https://reactnative.dev/ from inside your school's firewall?

Other websites work fine, but I haven't searched for blocked websites. 
The reactnative site works fine for me, but it also looks different in the terminal (i.e. no IP to name mapping):
```
$ host reactnative.dev
reactnative.dev has address 172.67.135.63
reactnative.dev has address 104.21.6.202
reactnative.dev has IPv6 address 2606:4700:3033::ac43:873f
reactnative.dev has IPv6 address 2606:4700:3036::6815:6ca
$ host 172.67.135.63
Host 63.135.67.172.in-addr.arpa. not found: 3(NXDOMAIN)
$ host 104.21.6.202
Host 202.6.21.104.in-addr.arpa. not found: 3(NXDOMAIN)
```

I talked about this issue with a college that knows much more than I about networks/internet, and he said (translated), that it is problematic, when DNS and IP don't point to each other. That happens, when several virtual hosts work behind a single address (Proxy/NAT or something else) and one was hacked.

I have only a minor understanding of such stuff, but I guess, only a small amount of GitHub based sites have this issue. Maybe only those with this IP address.

**Comment by zpao** [comment]
reactnative.dev is hosted elsewhere. Could go with one we're 100% sure is hosted on GitHub pages: https://facebook.github.io/watchman/. One of the hosts for that is 185.199.108.153.

It wouldn't surprise me if at some point somebody used GitHub pages site to DDOS in the past. GitHub is usually pretty good at catching those and shutting them down, but the damage may have been done.

Looks like we only have a single A record on pytorch.org, so we could probably make sure we have additional records to point at the other IP addresses GitHub uses, which might help your case.
```
185.199.108.153
185.199.109.153
185.199.110.153
185.199.111.153
```

**Comment by boeddeker** [comment]
Thank you. Now it works fine.

> Looks like we only have a single A record on pytorch.org, so we could probably make sure we have additional records to point at the other IP addresses GitHub uses, which might help your case.

I think someone did this, because now `pytorch.org` and `facebook.github.io` look similar:

```
$ host facebook.github.io
facebook.github.io has address 185.199.109.153
facebook.github.io has address 185.199.108.153
facebook.github.io has address 185.199.111.153
facebook.github.io has address 185.199.110.153
facebook.github.io has IPv6 address 2606:50c0:8000::153
facebook.github.io has IPv6 address 2606:50c0:8003::153
facebook.github.io has IPv6 address 2606:50c0:8001::153
facebook.github.io has IPv6 address 2606:50c0:8002::153
$ host pytorch.org
pytorch.org has address 185.199.108.153
pytorch.org has address 185.199.111.153
pytorch.org has address 185.199.110.153
pytorch.org has address 185.199.109.153
pytorch.org mail is handled by 5 alt2.aspmx.l.google.com.
pytorch.org mail is handled by 1 aspmx.l.google.com.
pytorch.org mail is handled by 10 alt4.aspmx.l.google.com.
pytorch.org mail is handled by 5 alt1.aspmx.l.google.com.
pytorch.org mail is handled by 10 alt3.aspmx.l.google.com.

```
