### ISSUE TITLE
Fix nightly version

### ISSUE THREAD

**Issue by 9bow** [pytorch/pytorch.github.io#986]
## 🕋 Website
 

I found a typo while reflecting the newly released version 1.11 on the [PyTorch Korean User Group website](https://pytorch.kr) (https://pytorch.kr)
Currently, the nightly version specified in the instructions on how to install PyTorch is `1.11`, as below screenshot. 
This version should be `1.12` which is for the next release.

## To Reproduce

Steps to reproduce the behavior (if applicable):

1. Go to `Get Started`
2. Click on `Start Locally` (default)
3. Scroll down to `Start Locally`

## Expected behavior

Nightly version should be `1.12`, not `1.11` that is currently released version.

## Screenshots

![image](https://user-images.githubusercontent.com/9343724/160276956-9e618f01-1730-43ed-950c-14f3def15a5b.png)

## Desktop (please complete the following information):

 - OS: macOS (x86_64)
 - Browser: Chrome
 - Version: 99.0.4844.83

**Comment by malfet** [comment]
Thank you very much for the report and the fix

**Comment by 9bow** [comment]
Thank you for reviewing very quickly!
